[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
memory_limit = 1000M

; # Extensions...
; extension_dir = "/usr/local/lib/php/extensions/"

; extension=swoole

; extension=bcmath
; extension=bz2
; extension=calendar
; extension=curl
; extension=ctype
; extension=dba
; extension=dom
; extension=enchant
; extension=exif
; extension=ffi
; extension=fileinfo
; extension=ftp
; extension=gd
; extension=gettext
; extension=gmp
; extension=iconv
; extension=imap
; extension=intl
; extension=ldap
; extension=mbstring
; extension=mysqli
; extension=odbc
; extension=openssl
; zend_extension=opcache
; extension=pcntl
; extension=pdo
; extension=pdo_dblib
; extension=pdo_mysql
; extension=pdo_odbc
; extension=pdo_pgsql
; extension=pdo_sqlite
; extension=posix
; extension=pgsql
; extension=pspell
; extension=redis
; extension=session
; extension=shmop
; extension=simplexml
; extension=snmp
; extension=soap
; extension=sockets
; extension=sodium
; extension=sqlite3
; extension=sysvmsg
; extension=sysvsem
; extension=sysvshm
; extension=tidy
; extension=xml
; extension=xsl
; extension=zip
; extension=imagick