[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
pidfile=/var/run/supervisord.pid

[program:php]
# process_name=%(program_name)s_%(process_num)02d
# numprocs=1
command=php -d variables_order=EGPCS /var/www/bin/laravels start
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-mail]
command=php /var/www/artisan queue:work redis --queue=mail --sleep=1 --tries=3
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
